### ISSUE TITLE
init throwing error when block permissions are set to restricted

### ISSUE THREAD

**Issue by keithwbloom** [amandadoughty/moodle-block_culactivity_stream#1]
I am not sure if this applies to the base CUL block architecture, but when I have a modified instance on my development environment and have block permissions set to be inaccessible for students (visible only to managers and admins), I get a script error from /yui/build/moodle-block_activity_stream-scroll-debug.js because Y.one('.block_activity_stream_lrs .reload') value returns NULL. I have fixed this by putting a test immediately above to see if Y.one('.block_activity_stream_lrs .reload') exists and is not NULL, then the block init can load successfully. If it is not valid, the whole init function is skipped.

**Comment by keithwbloom** [comment]
I am also new to collaborating through Git, so if my explanation is lacking any detail or directive, please let me know how I can further contribute.

**Comment by amandadoughty** [comment]
Apologies 4 years late seeing this. Closing as this code is in a try catch block.
